data = [
	{
		'title' : 'A Reliability Perspective of the Smart Grid',
		'abstract' : 'Increasing complexity of power grids, growing demand, and requirement for greater reliability, security and efficiency as well as environmental and energy sustainability concerns continue to highlight the need for a quantum leap in harnessing communication and information technologies. This leap toward a \"smarter\" grid is widely referred to as \"smart grid.\" A framework for cohesive integration of these technologies facilitates convergence of acutely needed standards, and implementation of necessary analytical capabilities. This paper critically reviews the reliability impacts of major smart grid resources such as renewables, demand response, and storage. We observe that an ideal mix of these resources leads to a flatter net demand that eventually accentuates reliability challenges further. A gridwide IT architectural framework is presented to meet these challenges while facilitating modern cybersecurity measures. This architecture supports a multitude of geographically and temporally coordinated hierarchical monitoring and control actions over time scales from milliseconds and up.'
	},
	{
		'title' : 'Cyber-Physical System Security for the Electric Power Grid',
		'abstract' : 'The development of a trustworthy smart grid requires a deeper understanding of potential impacts resulting from successful cyber attacks. Estimating feasible attack impact requires an evaluation of the grid\'s dependency on its cyber infrastructure and its ability to tolerate potential failures. A further exploration of the cyber-physical relationships within the smart grid and a specific review of possible attack vectors is necessary to determine the adequacy of cybersecurity efforts. This paper highlights the significance of cyber infrastructure security in conjunction with power application security to prevent, mitigate, and tolerate cyber attacks. A layered approach is introduced to evaluating risk based on the security of both the physical power applications and the supporting cyber infrastructure. A classification is presented to highlight dependencies between the cyber-physical controls required to support the smart grid and the communication and computations that must be protected from cyber attack. The paper then presents current research efforts aimed at enhancing the smart grid\'s application and infrastructure security. Finally, current challenges are identified to facilitate future research efforts.'
	},
	{
		'title' : 'Vulnerability Assessment of Cybersecurity for SCADA Systems',
		'abstract' : 'Vulnerability assessment is a requirement of NERC\'s cybersecurity standards for electric power systems. The purpose is to study the impact of a cyber attack on supervisory control and data acquisition (SCADA) systems. Compliance of the requirement to meet the standard has become increasingly challenging as the system becomes more dispersed in wide areas. Interdependencies between computer communication system and the physical infrastructure also become more complex as information technologies are further integrated into devices and networks. This paper proposes a vulnerability assessment framework to systematically evaluate the vulnerabilities of SCADA systems at three levels: system, scenarios, and access points. The proposed method is based on cyber systems embedded with the firewall and password models, the primary mode of protection in the power industry today. The impact of a potential electronic intrusion is evaluated by its potential loss of load in the power system. This capability is enabled by integration of a logic-based simulation method and a modul e for the power flow computation. The IEEE 30-bus system is used to evaluate the impact of attacks launched from outside or from within the substation networks. Countermeasures are identified for improvement of the cybersecurity.'
	},
	{
		'title' : 'Cybersecurity for Critical Infrastructures: Attack and Defense Modeling',
		'abstract' : 'Disruption of electric power operations can be catastrophic on national security and the economy. Due to the complexity of widely dispersed assets and the interdependences among computer, communication, and power infrastructures, the requirement to meet security and quality compliance on operations is a challenging issue. In recent years, the North American Electric Reliability Corporation (NERC) established a cybersecurity standard that requires utilities\' compliance on cybersecurity of control systems. This standard identifies several cyber-related vulnerabilities that exist in control systems and recommends several remedial actions (e. g., best practices). In this paper, a comprehensive survey on cybersecurity of critical infrastructures is reported. A supervisory control and data acquisition security framework with the following four major components is proposed: 1) real-time monitoring; 2) anomaly detection; 3) impact analysis; and 4) mitigation strategies. In addition, an attack-tree-based methodology for impact analysis is developed. The attack-tree formulation based on power system control (n)etworks is used to evaluate system-, scenario-, and leaf-level vulnerabilities by identifying the system\'s adversary objectives. The leaf vulnerability is fundamental to the methodology that involves port auditing or password strength evaluation. The measure of vulnerabilities in the power system control framework is determined based on existing cybersecurity conditions, and then, the vulnerability indices are evaluated.'
	},
	{
		'title' : 'Distributed Intrusion Detection System in a Multi-Layer Network Architecture of Smart Grids',
		'abstract' : 'The advent of the smart grid promises to usher in an era that will bring intelligence, efficiency, and optimality to the power grid. Most of these changes will occur as an Internet-like communications network is superimposed on top of the current power grid using wireless mesh network technologies with the 802.15.4, 802.11, and WiMAX standards. Each of these will expose the power grid to cybersecurity threats. In order to address this issue, this work proposes a distributed intrusion detection system for smart grids (SGDIDS) by developing and deploying an intelligent module, the analyzing module (AM), in multiple layers of the smart grid. Multiple AMs will be embedded at each level of the smart grid-the home area networks (HANs), neighborhood area networks (NANs), and wide area networks (WANs)-where they will use the support vector machine (SVM) and artificial immune system (AIS) to detect and classify malicious data and possible cyberattacks. AMs at each level are trained using data that is relevant to their level and will also be able to communicate in order to improve detection. Simulation results demonstrate that this is a promising methodology for supporting the optimal communication routing and improving system security through the identification of malicious network traffic.'
	},
	{
		'title' : 'An Authenticated Control Framework for Distributed Voltage Support on the Smart Grid',
		'abstract' : 'Existing and forthcoming devices at the residential level have the ability to provide reactive power support. Inverters which connect distributed generation such as solar panels and pluggable hybrid electric vehicles (PHEVs) to the grid are an example. Such devices are not currently utilized by the power system. We investigate the integration of these end-user reactive-power-capable devices to provide voltage support to the grid via a secure communications infrastructure. We determine effective locations in the transmission system and show how reactive power resources connected at those buses can be controlled. Buses belong to reactive support groups which parallel the regions of the secure communications architecture that is presented. Ultimately, our goal is to present how the smart grid can enable the utilization of available end-user devices as a resource to mitigate power system problems such as voltage collapse.'
	},
	{
		'title' : 'Reliability assessment of photovoltaic power systems: Review of current status and future perspectives',
		'abstract' : 'Quantitative reliability assessment of photovoltaic (PV) power system is an indispensable technology to assure reliable and utility-friendly integration of PV generation. This paper reviews the state-of-the-art technologies for evaluating the reliability of large-scale PV systems and the effect of PV interconnection on the reliability of local distribution system. The discussions are extended to emerging research topics including time varying and ambient-condition-dependent failure rates of critical PV system components, accurate operating models of PV generators in both interconnected and islanded modes, and the reliability evaluation of active distribution networks with PV penetration and transmission level Giga-PV system. A vision for the future research is presented, with a focus on the cyber-physical perspective of the PV reliability, modeling of PV voltage control scheme for reliability assessment, reliability assessment for PV systems under extreme events and PV reliability assessment considering cybersecurity. (C) 2012 Elsevier Ltd. All rights reserved.'
	},
	{
		'title' : 'Smart Grid Data Integrity Attacks',
		'abstract' : 'Real power injections at loads and generators, and real power flows on selected lines in a transmission network are monitored and transmitted over a SCADA network to the system operator. These are used in state estimation algorithms to make dispatch, re-balance and other energy management system [EMS] decisions. Coordinated cyber attacks on power meter readings can be designed to be undetectable by any bad data detection algorithm. These unobservable attacks present a serious threat to grid operations. Of particular interest are sparse attacks that involve the compromise of a modest number of meter readings. An efficient algorithm to find all unobservable attacks [under standard DC load flow approximations] involving the compromise of exactly two power injection meters and an arbitrary number of power meters on lines is presented. This requires O(n(2)m) flops for a power system with buses and line meters. If all lines are metered, there exist canonical forms that characterize all 3, 4, and 5-sparse unobservable attacks. These can be quickly detected with O(n(2)) flops using standard graph algorithms. Known-secure phasor measurement units [PMUs] can be used as countermeasures against a given collection of cyber attacks. Finding the minimum number of necessary PMUs is NP-hard. It is shown that p + 1 PMUs at carefully chosen buses are sufficient to neutralize a collection of cyber attacks.'
	},
        {
		'title' : 'Anomaly Detection for Cybersecurity of the Substations',
		'abstract' : 'Cybersecurity of the substations in a power system is a major issue as the substations become increasingly dependent on computer and communication networks. This paper is concerned with anomaly detection in the computer network environment of a substation. An anomaly inference algorithm is proposed for early detection of cyber-intrusions at the substations. The potential scenario of simultaneous intrusions launched over multiple substations is considered. The proposed detection method considers temporal anomalies. Potential intrusion events are ranked based on the credibility impact on the power system. Snapshots of anomaly entities at substations are described. Simulation results using the modified IEEE 118-bus system have shown the effectiveness of the proposed method for systematic identification. The result of this research is a tool to detect cyber-intrusions that are likely to cause significant damages to the power grid.'
	},
        {
		'title' : 'Protecting Smart Grid Automation Systems Against Cyberattacks',
		'abstract' : 'The smart grid moves new power grid automation systems from being proprietary and closed to the current state of information technology (IT) which is highly interconnected and open. But open and interconnected automation platforms bring about major security challenges. The power grid automation network has inherent security risks due to the fact that the systems and applications for the power grid were originally designed without much consideration of cybersecurity. This paper first introduces scope and functionalities of power grid, its automation and control system, and communications. Potential cyberattacks and their adverse impacts on power grid operation are discussed, a general SCADA cyberattack process is presented. This paper discusses the major challenges and strategies to protect smart grid against cyberattacks and finally proposes a conceptual layered framework for protecting power grid automation systems against cyberattacks without compromising timely availability of control and signal data. The proposed "bump-in-the-wire" approach also provides security protection for legacy systems which do not have enough computational power or memory space to perform security functionalities. The on-site system test of the developed prototype security system is briefly presented as well.'
	},
        {
            'title' : 'Toward a framework for managing information security for an electric power utility - CIGRE experiences',
            'abstract' : 'This paper deals with the increasingly important issue of proper handling of information security for electric power utilities. It is based on the efforts of CIGRE Joint Working Group (JWG) D2/B3/C2-01 on "Security for Information Systems and Intranets in Electric Power System" carried out between 2003 and 2006. The JWG has produced a technical brochure (TB), where the purpose to raise the awareness of information and cybersecurity in electric power systems, and gives some guidance on how to solve the security problem by focusing on security domain modeling, risk assessment methodology, and security framework building. Here in this paper, the focus is on the issue of awareness and to highlight some steps to achieve a framework for cybersecurity management. Also, technical considerations of some communication systems for substation automation are studied. Finally, some directions for further works in this vast area of information and cybersecurity are given.'
        },
        {
            'title' : 'From information security to cyber security',
            'abstract' : 'The term cyber security is often used interchangeably with the term information security. This paper argues that, although there is a substantial overlap between cyber security and information security, these two concepts are not totally analogous. Moreover, the paper posits that cyber security goes beyond the boundaries of traditional information security to include not only the protection of information resources, but also that of other assets, including the person him/herself. In information security, reference to the human factor usually relates to the role(s) of humans in the security process. In cyber security this factor has an additional dimension, namely, the humans as potential targets of cyber attacks or even unknowingly participating in a cyber attack. This additional dimension has ethical implications for society as a whole, since the protection of certain vulnerable groups, for example children, could be seen as a societal responsibility. (C) 2013 Elsevier Ltd. All rights reserved.'
        },
        {
            'title' : 'Optimal policy for software vulnerability disclosure',
            'abstract' : 'Software vulnerabilities represent a serious threat to cybersecurity, most cyberattacks exploit known vulnerabilities. Unfortunately, there is no agreed-upon policy for their disclosure. Disclosure policy (which sets a protected period given to a vendor to release the patch for the vulnerability) indirectly affects the speed and quality of the patch that a vendor develops. Thus, CERT/CC and similar bodies acting in the public interest can use disclosure to influence the behavior of vendors and reduce social cost. This paper develops a framework to analyze the optimal timing of disclosure. We formulate a model involving a social planner who sets the disclosure policy and a vendor who decides on the patch release. We show that the vendor typically releases the patch less expeditiously than is socially optimal. The social planner optimally shrinks the protected period to push the vendor to deliver the patch more quickly, and sometimes the patch release time coincides with disclosure. We extend the model to allow the proportion of users implementing patches to depend upon the quality (chosen by the vendor) of the patch. We show that a longer protected period does not always result in a better patch quality. Another extension allows for some fraction of users to use "work-arounds." We show that the possibility of work-arounds can provide the social planner with more leverage, and hence the social planner shrinks the protected period. Interestingly, the possibility of work-arounds can sometimes increase the social cost due to the negative externalities imposed by the users who are able to use the work-arounds on the users who are not.'
        },
        {
                'title' : 'A survey of emerging threats in cybersecurity',
                'abstract' : 'The exponential growth of the Internet interconnections has led to a significant growth of cyber attack incidents often with disastrous and grievous consequences. Malware is the primary choice of weapon to carry out malicious intents in the cyberspace, either by exploitation into existing vulnerabilities or utilization of unique characteristics of emerging technologies. The development of more innovative and effective malware defense mechanisms has been regarded as an urgent requirement in the cybersecurity community. To assist in achieving this goal, we first present an overview of the most exploited vulnerabilities in existing hardware, software, and network layers. This is followed by critiques of existing state-of-the-art mitigation techniques as why they do or don\'t work. We then discuss new attack patterns in emerging technologies such as social media, cloud computing, smartphone technology, and critical infrastructure. Finally, we describe our speculative observations on future research directions. Crown Copyright (c) 2014 Published by Elsevier Inc. All rights reserved.'
        },
        {
                'title' : 'An open virtual testbed for industrial control system security research',
                'abstract' : 'Industrial control system security has been a topic of scrutiny and research for several years, and many security issues are well known. However, research efforts are impeded by a lack of an open virtual industrial control system testbed for security research. This paper describes a virtual testbed framework using Python to create discrete testbed components including virtual devices and process simulators. The virtual testbed is designed such that the testbeds are inter-operable with real industrial control system devices and such that the virtual testbeds can provide comparable industrial control system network behavior to a laboratory testbed. Two virtual testbeds modeled upon actual laboratory testbeds have been developed and have been shown to be inter-operable with real industrial control system equipment and vulnerable to attacks in the same manner as a real system. Additionally, these testbeds have been quantitatively shown to produce traffic close to laboratory systems.'
        },
        {
                'title' : 'A control system testbed to validate critical infrastructure protection concepts',
                'abstract' : 'This paper describes the Mississippi State University SCADA Security Laboratory and Power and Energy Research laboratory. This laboratory combines model control systems from multiple critical infrastructure industries to create a testbed with functional physical processes controlled by commercial hardware and software over common industrial control system routable and non-routable networks. Laboratory exercises, functional demonstrations, and lecture material from the testbed have been integrated into a newly developed industrial control system cybersecurity course, into multiple other engineering and computer science courses, and into a series of short courses targeted to industry. Integration into the classroom allows the testbed to provide a workforce development function, prepares graduate students for research activities, and raises the profile of this research area with students. The testbed enables a research process in which cybersecurity vulnerabilities are discovered, exploits are used to understand the implications of the vulnerability on controlled physical processes, identified problems are classified by criticality and similarities in type and effect, and finally cybersecurity mitigations are developed and validated against within the testbed. Overviews of research enabled by the testbed are provided, including descriptions of software and network vulnerability research, a description of forensic data logger capability developed using the testbed to retrofit existing serial port MODBUS and DNP3 devices, and a description of intrusion detection research which leverages unique characteristics of industrial control systems. (C) 2011 Elsevier B.V. All rights reserved.'
        },
        {
                'title' : 'A framework for linking cybersecurity metrics to the modeling of macroeconomic interdependencies',
                'abstract' : 'Hierarchical decision making is a multidimensional process involving management of multiple objectives (with associated metrics and tradeoffs in terms of costs, benefits, and risks), which span various levels of a large-scale system. The nation is a hierarchical system as it consists multiple classes of decisionmakers and stakeholders ranging from national policymakers to operators of specific critical infrastructure subsystems. Critical infrastructures (e.g., transportation, telecommunications, power, banking, etc.) are highly complex and interconnected. These interconnections take the form of flows of information, shared security, and physical flows of commodities, among others. In recent years, economic and infrastructure sectors have become increasingly dependent on networked information systems for efficient operations and timely delivery of products and services. In order to ensure the stability, sustainability, and operability of our critical economic and infrastructure sectors, it is imperative to understand their inherent physical and economic linkages, in addition to their cyber interdependencies. An interdependency model based on a transformation of the Leontief input-output (I-O) model can be used for modeling: (1) the steady-state economic effects triggered by a consumption shift in a given sector (or set of sectors); and (2) the resulting ripple effects to other sectors. The inoperability metric is calculated for each sector; this is achieved by converting the economic impact (typically in monetary units) into a percentage value relative to the size of the sector. Disruptive events such as terrorist attacks, natural disasters, and large-scale accidents have historically shown cascading effects on both consumption and production. Hence, a dynamic model extension is necessary to demonstrate the interplay between combined demand and supply effects. The result is a foundational framework for modeling cybersecurity scenarios for the oil and gas sector. A hypothetical case study examines a cyber attack that causes a 5-week shortfall in the crude oil supply in the Gulf Coast area.'
        },
        {
                'title' : 'Percolation of localized attack on complex networks',
                'abstract' : 'The robustness of complex networks against node failure and malicious attack has been of interest for decades, while most of the research has focused on random attack or hub-targeted attack. In many real-world scenarios, however, attacks are neither random nor hub-targeted, but localized, where a group of neighboring nodes in a network are attacked and fail. In this paper we develop a percolation framework to analytically and numerically study the robustness of complex networks against such localized attack. In particular, we investigate this robustness in Erdos-Renyi networks, random-regular networks, and scale-free networks. Our results provide insight into how to better protect networks, enhance cybersecurity, and facilitate the design of more robust infrastructures.'
        },
        {
                'title' : 'Real-Time Intrusion Detection in Power System Operations',
                'abstract' : 'Increasing power system security is crucial to the future of the electric power grid. In this paper, we define a new class of cyberattacks to power systems-malicious modification of network data stored in an accessible database. Grounded in multivariate statistical process control, our approach to intrusion detection ensures data integrity in power system operations. We develop an algorithm that monitors power flow results and detects anomalies in the input values that could have been modified by cyberattacks. Our algorithm uses principal component analysis to separate power flow variability into regular and irregular subspaces. Analysis of the information in the irregular subspace determines whether the power system data has been compromised. We verify the efficacy of the algorithm using both the IEEE 24-bus and 118-bus reliability test systems. The results show that the developed algorithm is a promising enhancement to data security procedures in a control center.'
        },
        {
                'title' : 'Potential Cyberattacks on Automated Vehicles',
                'abstract' : 'Vehicle automation has been one of the fundamental applications within the field of intelligent transportation systems (ITS) since the start of ITS research in the mid-1980s. For most of this time, it has been generally viewed as a futuristic concept that is not close to being ready for deployment. However, recent development of "self-driving" cars and the announcement by car manufacturers of their deployment by 2020 show that this is becoming a reality. The ITS industry has already been focusing much of its attention on the concepts of "connected vehicles" (United States) or "cooperative ITS" (Europe). These concepts are based on communication of data among vehicles (V2V) and/or between vehicles and the infrastructure (V2I/I2V) to provide the information needed to implement ITS applications. The separate threads of automated vehicles and cooperative ITS have not yet been thoroughly woven together, but this will be a necessary step in the near future because the cooperative exchange of data will provide vital inputs to improve the performance and safety of the automation systems. Thus, it is important to start thinking about the cybersecurity implications of cooperative automated vehicle systems. In this paper, we investigate the potential cyberattacks specific to automated vehicles, with their special needs and vulnerabilities. We analyze the threats on autonomous automated vehicles and cooperative automated vehicles. This analysis shows the need for considerably more redundancy than many have been expecting. We also raise awareness to generate discussion about these threats at this early stage in the development of vehicle automation systems.'
        },
        {
                'title' : 'Decision support for Cybersecurity risk planning',
                'abstract' : 'Security countermeasures help ensure the confidentiality, availability, and integrity of information systems by preventing or mitigating asset losses from Cybersecurity attacks. Due to uncertainty, the financial impact of threats attacking assets is often difficult to measure quantitatively, and thus it is difficult to prescribe which countermeasures to employ. In this research, we describe a decision support system for calculating the uncertain risk faced by an organization under cyber attack as a function of uncertain threat rates, countermeasure costs, and impacts on its assets. The system uses a genetic algorithm to search for the best combination of countermeasures, allowing the user to determine the preferred tradeoff between the cost of the portfolio and resulting risk. Data collected from manufacturing firms provide an example of results under realistic input conditions. (C) 2011 Elsevier B.V. All rights reserved.'
        },
        {
                'title' : 'Cybersecurity Myths on Power Control Systems: 21 Misconceptions and False Beliefs',
                'abstract' : 'This paper presents and analyzes a selection of 21 "myths" identified from the authors\' experience as being the most common in power utilities and the most harmful to their cyber-security posture. For each one, tangible and referenced elements, typically sparse and dispersed, are presented in this single and up-to-date reference to support their rationalization. This paper also provides generic recommendations supporting power utilities on the ongoing and challenging process of dispelling the identified myths.'
        },
        {
                'title' : 'Survey and Taxonomy of Botnet Research through Life-Cycle',
                'abstract' : 'Of all current threats to cybersecurity, botnets are at the top of the list. In consequence, interest in this problem is increasing rapidly among the research community and the number of publications on the question has grown exponentially in recent years. This article proposes a taxonomy of botnet research and presents a survey of the field to provide a comprehensive overview of all these contributions. Furthermore, we hope to provide researchers with a clear perspective of the gaps that remain to be filled in our defenses against botnets. The taxonomy is based upon the botnet\'s life-cycle, defined as the sequence of stages a botnet needs to pass through in order to reach its goal. This approach allows us to consider the problem of botnets from a global perspective, which constitutes a key difference from other taxonomies that have been proposed. Under this novel taxonomy, we conclude that all attempts to defeat botnets should be focused on one or more stages of this life-cycle. In fact, the sustained hindering of any of the stages makes it possible to thwart a botnet\'s progress and thus render it useless. We test the potential capabilities of our taxonomy by means of a survey of current botnet research, and find it genuinely useful in understanding the focus of the different contributions in this field.'
        },
        {
                'title' : 'Efficient Computer Network Anomaly Detection by Changepoint Detection Methods',
                'abstract' : 'We consider the problem of efficient on-line anomaly detection in computer network traffic. The problem is approached statistically, as that of sequential (quickest) changepoint detection. A multi-cyclic setting of quickest change detection is a natural fit for this problem. We propose a novel score-based multi-cyclic detection algorithm. The algorithm is based on the so-called Shiryaev-Roberts procedure. This procedure is as easy to employ in practice and as computationally inexpensive as the popular Cumulative Sum chart and the Exponentially Weighted Moving Average scheme. The likelihood ratio based Shiryaev-Roberts procedure has appealing optimality properties, particularly it is exactly optimal in a multi-cyclic setting geared to detect a change occurring at a far time horizon. It is therefore expected that an intrusion detection algorithm based on the Shiryaev-Roberts procedure will perform better than other detection schemes. This is confirmed experimentally for real traces. We also discuss the possibility of complementing our anomaly detection algorithm with a spectral-signature intrusion detection system with false alarm filtering and true attack confirmation capability, so as to obtain a synergistic system.'
        },
        {
                'title' : 'Cybercriminal impacts on online business and consumer confidence',
                'abstract' : 'The information revolution, coupled with the strategic leveraging of the Internet, has exposed a number of relatively open societies to the dangers of cybercriminal and cyberterrorist acts, especially in commercial business transactions. With the development of e-commerce, this commercial dark side has become known as cybercrime and has taken on many forms that affect the perceptions of the way we shop online. Corporations should realize that these threats to their online businesses have strategic implications to their business future and take proper measures to ensure that these threats are eliminated or significantly reduced so that consumer confidence in the Internet as an alternative means of shopping is maintained. These counter measures, coined as cybersecurity, have been developed to ensure the safety of consumer privacy and information and allow for a carefree shopping experience. There is need for the development of models that will allow corporations to study the effects of cybercrime on online consumer confidence and to counter through leveraging the benefits associated with the latest developments in cybersecurity. With these two facets of e-commerce impacting the online consumer, corporations must ensure that the security measures taken will ultimately prevail to assure that consumers will continue to use the Internet to satisfy their shopping needs.'
        },
        {
                'title' : 'Pharmaceutical digital marketing and governance: illicit actors and challenges to global patient safety and public health',
                'abstract' : 'Background: Digital forms of direct-to-consumer pharmaceutical marketing (eDTCA) have globalized in an era of free and open information exchange. Yet, the unregulated expansion of eDTCA has resulted in unaddressed global public health threats. Specifically, illicit online pharmacies are engaged in the sale of purportedly safe, legitimate product that may in fact be counterfeit or substandard. These cybercriminal actors exploit available eDTCA mediums over the Internet to market their suspect products globally. Despite these risks, a detailed assessment of the public health, patient safety, and cybersecurity threats and governance mechanisms to address them has not been conducted. Discussion: Illicit online pharmacies represent a significant global public health and patient safety risk. Existing governance mechanisms are insufficient and include lack of adequate adoption in national regulation, ineffective voluntary governance mechanisms, and uneven global law enforcement efforts that have allowed proliferation of these cybercriminals on the web. In order to effectively address this multistakeholder threat, inclusive global governance strategies that engage the information technology, law enforcement and public health sectors should be established. Summary: Effective global "eHealth Governance" focused on cybercrime is needed in order to effectively combat illicit online pharmacies. This includes building upon existing Internet governance structures and coordinating partnership between the UN Office of Drugs and Crime that leads the global fight against transnational organized crime and the Internet Governance Forum that is shaping the future of Internet governance. Through a UNODC-IGF governance mechanism, investigation, detection and coordination of activities against illicit online pharmacies and their misuse of eDTCA can commence.'
        },
        {
                'title' : 'Cybersecurity: Stakeholder incentives, externalities, and policy options',
                'abstract' : 'Information security breaches are increasingly motivated by fraudulent and criminal motives. Reducing their considerable costs has become a pressing issue. Although cybersecurity has strong public good characteristics, most information security decisions are made by individual stakeholders. Due to the interconnectedness of cyberspace, these decentralized decisions are afflicted with externalities that can result in sub-optimal security levels. Devising effective solutions to this problem is complicated by the global nature of cyberspace, the interdependence of stakeholders, as well as the diversity and heterogeneity of players. The paper develops a framework for studying the co-evolution of the markets for cybercrime and cybersecurity. It examines the incentives of stakeholders to provide for security and their implications for the ICT ecosystem. The findings show that market and non-market relations in the information infrastructure generate many security-enhancing incentives. However, pervasive externalities remain that can only be corrected by voluntary or government-led collective measures. (C) 2009 Elsevier Ltd. All rights reserved'
        },
        {
                'title' : 'Quantitatively assessing the vulnerability of critical information systems: A new method for evaluating security enhancements',
                'abstract' : 'This paper proposes a new approach for assessing the organization\'s vulnerability to information-security breaches. Although Much research has been done on qualitative approaches, the literature on numerical approaches to quantify information-security risk is scarce. This paper Suggests a method to quantify risk in terms of a numeric value or "degree of cybersecurity". To help quantitatively measure the level of cybersecurity for a computer-based information system. we present two indices, the threat-impact index and the cyber-vulnerability index, based on vulnerability trees. By calculating and comparing the indices for various possible security enhancements, managers can select the best security enhancement choice, prioritize the choices by their relative effectiveness, and statistically justify spending resources on the selected choice. By qualifying information security quantitatively, the method can also help managers establish a specific target of security level that they can track. We illustrate the use of the proposed methodology on the security of supervisory control and data acquisition (SCADA) systems using data from the SCADA system test bed implemented at the University of Louisville as a case study, and then show the use of the proposed indices on this information system before and after two security enhancements. (C) 2008 Elsevier Ltd. All rights reserved.'
        },
        {
                'title' : 'A security mechanism of web services-based communication for wind power plants',
                'abstract' : 'The IEC 61400-25 standard has defined the mapping of wind power-plant information model to web services (WS). Ensuring the security of WS-based communication for wind power plants is an unsolved problem. WS-Security is a standard used to deal with the security requirements in applications of web services, while the username/password and X.509 certificates are security tokens most commonly used in electric power utilities. We propose a security mechanism that deals with the requirements of authentication, integrity, nonreputation, and confidentiality across the communication process based on WS-Security and the two security tokens. The security mechanism is implemented by an extension of simple object-access protocol message, design of the security agent, and the related security message-processing algorithm. An instance is modeling based on IEC 61400-25 to demonstrate the security-enhanced remote control of wind power plants. The result supports the usefulness of the security mechanism for WS-based wind power plants communication.'
        },
        {
                'title' : 'Multiattribute SCADA-Specific Intrusion Detection System for Power Networks',
                'abstract' : 'The increased interconnectivity and complexity of supervisory control and data acquisition (SCADA) systems in power system networks has exposed the systems to a multitude of potential vulnerabilities. In this paper, we present a novel approach for a next-generation SCADA-specific intrusion detection system (IDS). The proposed system analyzes multiple attributes in order to provide a comprehensive solution that is able to mitigate varied cyber-attack threats. The multiattribute IDS comprises a heterogeneous white list and behavior-based concept in order to make SCADA cybersystems more secure. This paper also proposes a multilayer cyber-security framework based on IDS for protecting SCADA cybersecurity in smart grids without compromising the availability of normal data. In addition, this paper presents a SCADA-specific cybersecurity testbed to investigate simulated attacks, which has been used in this paper to validate the proposed approach.'
        }
]
